### ISSUE TITLE
[长期有效] 寻求新的 Owner/主要维护者

### ISSUE THREAD

**Issue by SeaHOH** [LifeActor/ykdl#565]
ykdl 是由 @zhangn1985 从 [you-get](https://github.com/soimort/you-get) fork 而开始的项目，因各种[缘由](https://github.com/SeaHOH/ykdl/issues/554)现相关权限暂时转由我 (@SeaHOH) 来掌有。本人是非专业人士 (即外行)，因而此项目仍然需要一位经验丰富主要的维护者，以维持健康发展。

现诚邀有兴趣的人士加入，我将在简单了解后转移 Owner 权限于条件合适者。毕竟我是外行，具体条件希望应邀者可以自主展示，主旨就是能维持此项目健康发展的能力。而我本人在移交权限后，仍可长期在能力范围内参与项目发展。

嘛，好像没啥可写的了，以上。

**Comment by LifeActor** [comment]
> 由@zhangn1985从[你得到](https://github.com/soimort/you-get)分叉而开始的项目，因各种[缘由](https://github.com/SeaHOH/ykdl/issues/554)相关权限暂时转由我（@SeaHOH）来掌有。本人是非专业人士（即外行），因此此项目仍然需要一位经验丰富的主要的维护者，以维持健康发展。
> 
> 现在诚邀有兴趣的人加入，我将在简单了解后转移所有者权限于条件合适者。毕竟我是外行，具体条件希望应邀者可以自主展示，目的就是能够维持这个项目健康发展的能力。而我本人在移交权限后，仍可长期在能力范围内参与项目发展。
> 
> 嗯，要求啥可写的了，以上。

我可以接手这个项目继续开发，目前可使用python php nodejs golang开发后端项目，可使用vue3 recat amis boostrap layui等开发前端项目，不过看这个时间2024年8月19日16:16:06，好像有点时隔千年来相会的意味了

**Comment by SeaHOH** [comment]
@LifeActor 后续沟通我已发到你的邮箱，请注意查收。

**Comment by SeaHOH** [comment]
@LifeActor 仍未收到回信，你的邮箱还在使用吗？没有的话，也可以在这里交流。无论如何，请回复我。

**Comment by LifeActor** [comment]
@SeaHOH 十分抱歉，未能及时回复您的邮件，工作日的原因(一般假期冲浪)。
详读您的来信，现正式回复如下：
    我从事计算机软件行业初期基本担任win32 PE文件的逆向分析工作，后续扩展了 win64 pe 和 web前端的脚本逆向分析工作，您给出的两个功能完善的选择，我都可以扩展，但 交互模式 的完善，因没有产品经理的工作经历，遂不明白具体的需求细节。
    我计划近日fork项目后进行扩展开发，随后提交PR。
十分感谢您的回复，顺祝商祺

**Comment by SeaHOH** [comment]
@LifeActor 收到，那后续就在邮件沟通，更方便些。
