### ISSUE TITLE
这种情况是否在下载了？ [py313]

### ISSUE THREAD

**Issue by ebfming** [LifeActor/ykdl#643]
![微信截图_20241015115820](https://github.com/user-attachments/assets/d16bcbc0-e24c-48b4-840d-89503c243e02)

输出命令是开始下载了，但是等了好久没有找到下载的文件

**Comment by SeaHOH** [comment]
没有吧，进度条都没出来，像是没连上下载主机。如果始终如此，可以加调试命令查看。
试过可以下载，但是很慢，返回的几个主机都差不多慢。

**Comment by ebfming** [comment]
> 没有吧，进度条都没出来，像是没连上下载主机。如果始终如此，可以加调试命令查看。 试过可以下载，但是很慢，返回的几个主机都差不多慢。

![微信截图_20241015141006](https://github.com/user-attachments/assets/2760c945-1e6a-4df7-9207-82818b82650f)

我开启了调试模式，好像报告了一个错误。
我不懂py，可以帮我看一下是什么问题嘛？

**Comment by SeaHOH** [comment]
不兼容 py314

**Comment by ebfming** [comment]
> 不兼容 py313，稍后会修复。

好的，期待早日能用上
